import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { compileCsl } from '../src/csl/compiler.js'
import { kernelManifest } from '../src/effects/specs.js'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const sourceRoot = resolve(root, 'src/effects/sources')
const outputPath = resolve(root, 'src/effects/generated/kernels.js')

const entries = []
for (const [key, relativePath] of kernelManifest) {
  const sourcePath = resolve(sourceRoot, relativePath)
  const source = await readFile(sourcePath, 'utf8')
  const compiled = compileCsl(source, { sourceName: `src/effects/sources/${relativePath}` })
  entries.push(`  [${JSON.stringify(key)}, (${compiled.generatedSource})]`)
}

const output = `// Generated by scripts/generate-kernels.js. Do not edit by hand.\nimport { cslRuntime as $runtime } from '../../csl/runtime.js'\n\nconst $empty = Object.freeze({})\n\nexport const kernels = new Map([\n${entries.join(',\n')}\n])\n`

await mkdir(dirname(outputPath), { recursive: true })
await writeFile(outputPath, output)
console.log(`Generated ${entries.length} CSL kernels`) // eslint-disable-line no-console
